<?php  if ( ! defined('APP_PATH')) exit('No direct script access allowed');
$language = array (
    'device_langs' => array(
        1 => '已激活',
        0 => '未激活',
    ),
    'bus_region_comment' => '{$region}默认页面,请匆删除',

    'banner_status' => array(
        0 => '数据不完整',
        1 => '审核中',
        2 => '审核通过',
        3 => '投放中',
        4 => '不通过',
    ),


    // 登录
    'PAuth.Login.StateError' => '本次登录无效，请返回登录页面刷新重试',
    'PAth.Common.ApiTokenFailed' => '系统繁忙，请稍后重试(OP01)', // 无法获取Token
    'PAth.Login.ApiTokenFailed2' => '系统繁忙，请稍后重试(OP02)', // 无法获取用户资料
    'PAuth.Login.NotOLOUser' => '您的平台账号异常，请与我们联系',
    'PCommon.Trans.Failed' => '系统繁忙，请稍后再试（TRANS01）',
    'PAuth.Common.NotLogin' => '您还没有登录，请选登录后再操作',
    'PAuth.Common.AccessDenied' => '您没有操作权限，请与贵方的管理员联系开通权限',
    'PAuth.Common.OpenTokenEmpty' => '系统繁忙，请稍后再试（OP03）', // 无法获取open的令牌
    'PAuth.Callback.AuthCodeEmpty' => '系统繁忙，请稍后再试（AU01）', //无效的回调请求
    'PAuth.Callback.InsertAppInfoError' => '系统繁忙，请稍后重试（AP01）', // 往数据库写入APP信息失败
    'PAuth.Callback.InsertAppTeamError' => '系统繁忙，请稍后重试（OT01）', // 往数据库写小组信息失败
    'PAuth.TeamInvite.StateNull' => '本次邀请无效，请与您的好友联系',
    'PAuth.TeamInvite.StateExpire' => '邀请已经过期，请重新找您的好友要邀请地址',
    'PAuth.TeamInvite.TeamInvaild' => '小组已经解散，请与您的好友联系',
    'PAuth.Login.IsMembered' => '您已经是该小组的成员，无需重复加入',
    'PAuth.TeamAccept.Success' => '您已经成功申请加入该小组，请等待小组的管理员审核',

    // 微信通用
    'PWxMsg.Common.InvaildParams' => '无效的消息参数',

    'PCate.Common.WxAppIdNotExists' => '非常抱歉，摇E摇无法正确处理这个公众号，请您解绑后重新绑定',
    'PCate.Common.WxAppForbidden' => '您不是这个公众号的成员，请先申请成为该公众号的成员（如果已经申请，请与管理员联系，未通过审核也是没有权限的）',
    'PCate.Post.TitleNull' => '分类名称必须填写',
    'PCate.Save.Success' => '分类添加成功:)',

    // 小组
    'PTeam.Invite.TeamNull' => '请选择要邀请的小组',
    'PTeam.Common.NotLeader' => '您不是小组的管理员，无法邀请',
    'PTeam.Common.InvaildInput' => '无效参数',
    'PTeam.Accept.Success' => '成功处理',
    'PTeam.Remove.Success' => '已经移除',
    'PTeam.Accept.UpdateFailed' => '您已经处理过该请求', // 写同意数据时失败
    'PTeam.Remove.UpdateFailed' => '移除失败',

    // 微信菜单
    'PWxMenu.Rsync.InvaildAppId' => '非常抱歉，摇E摇无法正确处理这个公众号，请您解绑后重新绑定',
    'PSystem.Common.InvaildInput' => '无效输入',
    'PWxMenu.Sync.Success' => '您的菜单已经同步到微信平台，且将在24小时内对所有用户生效',
    'PCommon.System.Unauth' => '您还没有登录，请选登录后再操作',
    'PCommon.System.UserNotExists' => '摇E摇无法找到该用户，请您退出后再重新登录',
    'PUserTeam.Create.InsertError' => '系统繁忙，请稍后重试（OT02)',  // 创建小组时失败
    'PTeam.Join.Failed' => '加入小组失败',

    // 语音红包
    'PVoiceRed.Send.ParameterError' => '抱歉，参数错误！',
    'PVoiceRed.Send.Repeat' => '抱歉，您已领过红包！',
    'PVoiceRed.Send.ActExpired' => '抱歉，活动未开始或已结束！',
    'PVoiceRed.Send.Congratulation' => '恭喜，红包已发出，请查收！',
    'PVoiceRed.Send.GetRed' => '领取红包',

    'PHongBao.Common.Limited' => '红包已经发光了，下次赶早！',
    'PHongBao.Common.Overflow' => '您已经领取过多本次活动红包，无法领取更多！',
    'PHongBao.Common.OverflowDay' => '您今天已经领取过活动红包，明天再试！',
    'PWxRedCash.Common.InvaildMoney' => '哎呀，出了点小错(MI01)',

    //通用
    'Common.ParameterError' => '参数错误！请重试！',
    'Common.SaveSuccess' => '保存成功！',
    'Common.SaveFail' => '保存失败！',
    'Common.DelSuccess' => '删除成功！',
    'Common.DelFail' => '删除失败！',
    'Common.ActNotExist' => '活动还未开始，敬请期待！',
    'Common.SystemError1' => '抱歉，系统繁忙！(01)',

    //模仿秀
    'ImitateShowManage.Common.AddFail' => '添加失败！请重试！',
    'ImitateShowManage.Common.AddSuccess' => '添加成功！',
    'ImitateShowManage.Common.ParameterError' => '参数错误！请重试！',
    'ImitateShowManage.Common.ModSuccess' => '修改成功！',
    'ImitateShowManage.Common.DelSuccess' => '删除成功！',
    'ImitateShowManage.Common.ActExpired' => '活动不存在！敬请期待！',
    'ImitateShowManage.Common.NotAuthLogin' => '未授权登录!',
    'ImitateShowManage.Common.IntrNotNull' => '简介不能为空！',
    'ImitateShowManage.Common.SaveSuccess' => '保存成功!',
    'ImitateShowManage.Common.SaveFail' => '保存失败！',
    'ImitateShowManage.Common.InvalidVideoUnique' => '无效video_unique！',
    'ImitateShowManage.Common.DataNull' => '无数据！',
    'ImitateShowManage.Common.InvalidVideoId' => '无效video_id！',
    'ImitateShowManage.Common.CommonIdIsNull' => '无效评论ID!',
    'ImitateShowManage.Common.DoFail' => '操作失败！',
    'ImitateShowManage.Common.GetShareParamsFail' => '获取分享参数失败！',

    'ImitateShowManage.VideoStatus.Play' => '可以正常播放',
    'ImitateShowManage.VideoStatus.TranscodingFails' => '转码失败',
    'ImitateShowManage.VideoStatus.AuditFailure' => '审核失败',
    'ImitateShowManage.VideoStatus.ErrorSources' => '片源错误',
    'ImitateShowManage.VideoStatus.PublishFailed' => '发布失败',
    'ImitateShowManage.VideoStatus.UploadFailed' => '上传失败',
    'ImitateShowManage.VideoStatus.Processing' => '处理中',
    'ImitateShowManage.VideoStatus.UnderReview' => '审核中',
    'ImitateShowManage.VideoStatus.NoVideoSource' => '无视频源',
    'ImitateShowManage.VideoStatus.UploadInitialization' => '上传初始化',
    'ImitateShowManage.VideoStatus.VideoUploading' => '视频上传中',
    'ImitateShowManage.VideoStatus.Disable' => '停用',


    'PSignin.Common.Signed' => '您今天已经签到过，无需重复签到！',

    'PBargain.Common.InvaildId' => '无效的活动编号！',
    'PBargain.Common.InvaildCode' => '无效的验证码！',
    'PBargain.Common.InvaildQrCode1' => '无效二维码，请让用户刷新一下再尝试扫描！(01)',
    'PBargain.Common.InvaildQrCode2' => '二维码已经过期，请让用户刷新一下后再扫描。',
    'PBargain.Common.InvaildQrCode3' => '无效二维码，请让用户刷新一下再尝试扫描！(03)',
    'PBargain.Common.InvaildQrCode4' => '无效二维码，请让用户刷新一下再尝试扫描！(04)',
    'PBargain.Common.InvaildQrCode5' => '无效二维码，请让用户刷新一下再尝试扫描！(05)',
    'PBargain.Common.InvaildQrCode6' => '无效二维码，请让用户刷新一下再尝试扫描！(06)',
    'PBargain.Common.InvaildQrCode7' => '无效二维码，请让用户刷新一下再尝试扫描！(07)',
    'PBargain.Common.IsBinding' => '您已绑定过！',
    'PBargain.Common.BindingSuccess' => '绑定成功！',
    'PBargain.Common.BindingFail' => '绑定失败！',
    'PBargain.Common.WeightsError' => '权重必须大于0',
    'PBargain.Common.YouFail' => '很遗憾，您没有中奖！',
    'PBargain.Common.Used' => '该二维码已使用过！',
    'PBargain.Common.NoPrize' => '您还没有奖品，请先添加！',
    'PBargain.Common.UseSuccess' => '恭喜，核销成功！',
    'PBargain.Common.UseFail' => '抱歉，核销失败！',
    'PBargain.Common.NotPermission' => '抱歉，您没有核销权限，请联系相应商户获取权限！',
    'PBargain.Common.WaintingGameOver' => '请等待活动结束再查看中奖名单！',
    'PBargain.ChangeStatus.Success' => '保存成功，状态已经改变！',
    'PBargain.ChangeStatus.ParameterError' => '对不起，参数错误！请重试！',
    'PBargain.ChangeStatus.ActExpired' => '活动还未开始，敬请期待！',
    'PBargain.ChangeStatus.NotAuthLogin' => '未授权登录！',
    'PBargain.ChangeStatus.PhoneNotNull' => '电话号码不能为空！',
    'PBargain.ChangeStatus.NameNotNull' => '姓名不能为空！',
    'PBargain.ChangeStatus.AddrNotNull' => '地址不能为空！',
    'PBargain.ChangeStatus.SystemBusy01' => '系统繁忙，请稍候再试！(01)',
    'PBargain.ChangeStatus.SystemBusy02' => '系统繁忙，请稍候再试！(02)',
    'PBargain.ChangeStatus.SystemBusy03' => '系统繁忙，请稍候再试！(03)',
    'PBargain.ChangeStatus.JoinedFull' => '来晚了-_||| 东西已经被抢光了，下次赶早！',
    'PBargain.ChangeStatus.JoinedFail' => '砍价失败！',
    'PBargain.ChangeStatus.PriceIsBot' => '已经最底价了！',
    'PBargain.ChangeStatus.UserBargained' => '用户已砍价过！',
    'PBargain.ChangeStatus.ExportSuccess' => '导出成功！',
    'PBargain.ChangeStatus.ExportFail' => '导出失败！',
    'PBargain.ChangeStatus.DelSuccess' => '删除成功！',
    'PBargain.ChangeStatus.DelFail' => '删除失败！',
    'PBargain.ChangeStatus.SetNumAndPrice' => '请设置价格--人数区间！',
    'PBargain.ChangeStatus.BeginPrice' => '开始区间为原价！',
    'PBargain.ChangeStatus.BetweenPrice' => '区间必须在原价和底价之间！',
    'PBargain.ChangeStatus.RangeNotRepeat' => '区间必须连续且不重复！',
    'PBargain.ChangeStatus.RangeLeftLTRight' => '区间必须左边大于右边！',
    'PBargain.ChangeStatus.SaveSuccess' => '保存成功！',
    'PBargain.ChangeStatus.SaveFail' => '保存失败！',
    'PBargain.Common.InvaildMember' => '您还没有参与活动！',
    'PBargain.Common.InvalidGender1' => '本次活动只有男性才能参与！',
    'PBargain.Common.InvalidGender2' => '本次活动只有女性才能参与！',
    'PBargain.ChangeStatus.Expired' => '对不起，活动已过期！',
    'PBargain.DoBargain.Overload' => '对不起，你已经帮好友砍过价（自己报名参与砍价算一次），不能再帮更多好友砍！',

    'BoBing.Common.SaveSuccess' => '保存成功！',
    'BoBing.Common.SaveFail' => '保存失败！',
    'BoBing.Common.DelSuccess' => '删除成功！',
    'BoBing.Common.DelFail' => '删除失败！',

    'Business.Common.CodeNotNull' => '验证码不能为空！',
    'Business.Common.SystemBusy01' => '系统繁忙！(01)',
    'Business.Common.SystemBusy02' => '系统繁忙！(02)',
    'Business.Common.SystemBusy03' => '系统繁忙！(03)',
    'Business.Common.SystemBusy04' => '系统繁忙！(04)',
    'PActMidAutumn.Common.NoLogin' => '请从微信登录！',
    'PActMidAutumn.Common.InvalidId' => '无效的活动编号！',
    'PActMidAutumn.Common.InvalidRid' => '无效的包间编号！',
    'PActMidAutumn.Common.NotStart' => '活动还未开始！',
    'PActMidAutumn.Common.Ended' => '活动已经结果！',
    'PActMidAutumn.Common.ManaBusy' => '系统繁忙，请稍后重试（Mana)',
    'PActMidAutumn.Common.LuckBusy' => '系统繁忙，请稍后重试（Luck)',
    'PActMidAutumn.Common.InvalidRoom' => '无效的包间！',
    'PActMidAutumn.Luck.Overflow' => '您已经没有次数了!',
    'PActMidAutumn.Common.NotInRoom' => '您还没有选择包箱，请先选择!',
    'PActMidAutumn.Common.InvalidAddr' => '请输入有效的通讯地址！',
    'PActMidAutumn.Common.InvalidPhone' => '请输入有效的联系电话！',
    'PActMidAutumn.Common.InvalidName' => '请输入有效的联系人!',
    'PActMidAutumn.Common.Locked' => '您的请求过于频繁，请稍后再试！',
    'PActMidAutumn.Common.NotHitName' => '幸运奖',

    'Vote.Common.InvalidCode1' => '无效验证码！(01)',
    'Vote.Common.InputName' => '请输入商户名称！',
    'Vote.Common.PleaseFollow' => '请关注公众号！',
    'Vote.Common.ParameterError1' => '抱歉，参数错误！(01)',
    'Vote.Common.ParameterError2' => '抱歉，参数错误！(02)',
    'Vote.Common.ParameterError3' => '抱歉，参数错误！(03)',
    'Vote.Common.ParameterError4' => '抱歉，参数错误！(04)',
    'Vote.Common.ParameterError5' => '抱歉，参数错误！(05)',
    'Vote.Common.PostRepeat' => '请勿重复提交！',
    'Vote.Common.AccessError' => '用户未正常访问！',
    'Vote.Common.DataNull' => '数据为空！',
    'Vote.Common.VoteTimesNull' => '投票次数已用完！',
    'Vote.Common.SorryForNotEnoughVotetimes' => '抱歉，您剩余的投票次数不足！您剩余投票数为：',
    'Vote.Common.VoteFail' => '投票失败！',
    'Vote.Common.VoteRepeat' => '请勿刷票！',
    'Vote.Common.AddCategoryFirst' => '请到先到分类管理里添加该活动的分类！',
    'Vote.Common.NotPassReasonNull' => '审核未通过原因不能为空！',
    'Vote.Common.PassOrNot' => '请选择审核通过与否！',
    'Vote.Common.InputActName' => '请输入活动名称！',
    'Vote.Common.InputCategoryName' => '请输入分类名称！',
    'Vote.Common.CheckSuccess' => '审核成功！',
    'Vote.Common.CheckFail' => '审核失败！',
    'Vote.Common.InputSearchKeyword' => '请输入搜索关键字！',
    'Vote.Common.BusinessNameNotNull' => '商户名称不能为空！',
    'Vote.Common.UNameNotNull' => '推荐人手机不能为空！',
    'Vote.Common.UAddrNotNull' => '推荐人地址不能为空！',
    'Vote.Common.SearchNull' => '抱歉，无相应商户！',

);
